import { Series, Season, Episode, Genre } from '../src/types';

export const INITIAL_GENRES: Genre[] = [
  { id: 'g-romance', name: 'Romance', slug: 'romance', icon: 'Heart' },
  { id: 'g-drama', name: 'Drama', slug: 'drama', icon: 'Film' },
  { id: 'g-thriller', name: 'Thriller', slug: 'thriller', icon: 'Flame' },
  { id: 'g-short-films', name: 'Short Films', slug: 'short-films', icon: 'Tv' },
  { id: 'g-mystery', name: 'Mystery', slug: 'mystery', icon: 'Search' },
  { id: 'g-action', name: 'Action', slug: 'action', icon: 'Zap' },
];

// High reliability reliable public video URLs (MP4 with audio) for micro drama playback
const SAMPLE_VIDEOS = [
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
];

export const INITIAL_SERIES: Series[] = [
  {
    id: 'series-1',
    title: 'The Last Promise',
    slug: 'the-last-promise',
    posterUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=600&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=1600&auto=format&fit=crop&q=80',
    description: 'Separated by destiny and reunited under dangerous circumstances in Udaipur. Ananya and Kabir must confront ancestral secrets before time runs out.',
    genres: ['Romance', 'Drama'],
    language: 'Hindi',
    cast: ['Priya Sharma', 'Kabir Mehra', 'Alok Verma'],
    director: 'Vikramaditya Sengupta',
    trailerUrl: SAMPLE_VIDEOS[0],
    status: 'Completed',
    releaseDate: '2025-01-10',
    isFeatured: true,
    isTrending: true,
    isNewRelease: true,
    homepageOrder: 1,
    totalViews: 24500,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'series-2',
    title: 'Midnight in Mumbai',
    slug: 'midnight-in-mumbai',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1600&auto=format&fit=crop&q=80',
    description: 'When an elite diamond heist rocks Marine Drive during a monsoon blackout, a rogue inspector races against corrupt kingpins and ruthless syndicate killers.',
    genres: ['Thriller', 'Drama'],
    language: 'Hindi',
    cast: ['Raghav Joshi', 'Sanya Malhotra', 'Devendra Rao'],
    director: 'Anurag Kashyap',
    trailerUrl: SAMPLE_VIDEOS[1],
    status: 'Ongoing',
    releaseDate: '2025-02-15',
    isFeatured: false,
    isTrending: true,
    isNewRelease: true,
    homepageOrder: 2,
    totalViews: 38200,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'series-3',
    title: 'Love at First Beat',
    slug: 'love-at-first-beat',
    posterUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1600&auto=format&fit=crop&q=80',
    description: 'An indie street rapper from Chennai meets an orthodox Carnatic vocalist in Bangalore. Can their contrasting rhythms blend into an unforgettable anthem?',
    genres: ['Romance', 'Short Films'],
    language: 'Tamil / Hindi',
    cast: ['Karthik Raman', 'Meera Iyer', 'Rohan Seth'],
    director: 'Gautham Menon',
    trailerUrl: SAMPLE_VIDEOS[2],
    status: 'Completed',
    releaseDate: '2025-03-01',
    isFeatured: false,
    isTrending: false,
    isNewRelease: true,
    homepageOrder: 3,
    totalViews: 19800,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const INITIAL_SEASONS: Season[] = [
  {
    id: 'season-1-1',
    seriesId: 'series-1',
    seasonNumber: 1,
    title: 'Season 1',
    description: 'The fateful reunion and uncovering the ancient royal diary.',
    orderIndex: 1,
  },
  {
    id: 'season-2-1',
    seriesId: 'series-2',
    seasonNumber: 1,
    title: 'Season 1',
    description: 'The 48-hour manhunt across rain-drenched Mumbai streets.',
    orderIndex: 1,
  },
  {
    id: 'season-3-1',
    seriesId: 'series-3',
    seasonNumber: 1,
    title: 'Season 1',
    description: 'Fusion frequencies, studio clashes, and runaway feelings.',
    orderIndex: 1,
  },
];

export const INITIAL_EPISODES: Episode[] = [
  // Series 1 Episodes
  {
    id: 'ep-1-1',
    seriesId: 'series-1',
    seasonId: 'season-1-1',
    episodeNumber: 1,
    title: 'The Meeting',
    description: 'Kabir arrives at the vintage lake palace only to encounter Ananya under an unexpected torrential storm.',
    videoUrl: SAMPLE_VIDEOS[0],
    thumbnailUrl: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=800&auto=format&fit=crop&q=80',
    duration: 165,
    durationFormatted: '2m 45s',
    releaseDate: '2025-01-10',
    status: 'Published',
    isFeatured: true,
    orderIndex: 1,
    viewsCount: 8900,
    likesCount: 642,
    commentsCount: 38,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'ep-1-2',
    seriesId: 'series-1',
    seasonId: 'season-1-1',
    episodeNumber: 2,
    title: 'The Secret',
    description: 'A locked chest in the royal archives reveals a letter dated fifty years ago with both their family crests.',
    videoUrl: SAMPLE_VIDEOS[1],
    thumbnailUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    duration: 190,
    durationFormatted: '3m 10s',
    releaseDate: '2025-01-12',
    status: 'Published',
    orderIndex: 2,
    viewsCount: 7200,
    likesCount: 512,
    commentsCount: 29,
    createdAt: new Date(Date.now() - 23 * 86400000).toISOString(),
  },
  {
    id: 'ep-1-3',
    seriesId: 'series-1',
    seasonId: 'season-1-1',
    episodeNumber: 3,
    title: 'The Truth',
    description: 'Ananya confronts her grandfather about the feud that forced the families into bitter separation.',
    videoUrl: SAMPLE_VIDEOS[2],
    thumbnailUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&auto=format&fit=crop&q=80',
    duration: 145,
    durationFormatted: '2m 25s',
    releaseDate: '2025-01-15',
    status: 'Published',
    orderIndex: 3,
    viewsCount: 6400,
    likesCount: 480,
    commentsCount: 22,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'ep-1-4',
    seriesId: 'series-1',
    seasonId: 'season-1-1',
    episodeNumber: 4,
    title: 'Broken Vows',
    description: 'A midnight confrontation at the lake shore tests Kabir’s loyalty against his family pride.',
    videoUrl: SAMPLE_VIDEOS[3],
    thumbnailUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&auto=format&fit=crop&q=80',
    duration: 180,
    durationFormatted: '3m 00s',
    releaseDate: '2025-01-18',
    status: 'Published',
    orderIndex: 4,
    viewsCount: 5900,
    likesCount: 410,
    commentsCount: 19,
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  {
    id: 'ep-1-5',
    seriesId: 'series-1',
    seasonId: 'season-1-1',
    episodeNumber: 5,
    title: 'Eternity',
    description: 'As dawn rises over the palace gates, Kabir makes a daring promise that will redefine their lives forever.',
    videoUrl: SAMPLE_VIDEOS[4],
    thumbnailUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=800&auto=format&fit=crop&q=80',
    duration: 210,
    durationFormatted: '3m 30s',
    releaseDate: '2025-01-20',
    status: 'Published',
    orderIndex: 5,
    viewsCount: 5400,
    likesCount: 390,
    commentsCount: 34,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },

  // Series 2 Episodes (Midnight in Mumbai)
  {
    id: 'ep-2-1',
    seriesId: 'series-2',
    seasonId: 'season-2-1',
    episodeNumber: 1,
    title: 'The Blackout',
    description: 'Mumbai power grid fails at 2:14 AM. In five minutes, 200 million rupees worth of raw uncut diamonds vanish.',
    videoUrl: SAMPLE_VIDEOS[1],
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    duration: 175,
    durationFormatted: '2m 55s',
    releaseDate: '2025-02-15',
    status: 'Published',
    isFeatured: true,
    orderIndex: 1,
    viewsCount: 11200,
    likesCount: 890,
    commentsCount: 45,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'ep-2-2',
    seriesId: 'series-2',
    seasonId: 'season-2-1',
    episodeNumber: 2,
    title: 'Shadows on Marine Drive',
    description: 'Inspector Raghav recovers a burned burner phone on the sea wall with coordinates pointing to an abandoned dock.',
    videoUrl: SAMPLE_VIDEOS[2],
    thumbnailUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80',
    duration: 185,
    durationFormatted: '3m 05s',
    releaseDate: '2025-02-18',
    status: 'Published',
    orderIndex: 2,
    viewsCount: 9400,
    likesCount: 710,
    commentsCount: 32,
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'ep-2-3',
    seriesId: 'series-2',
    seasonId: 'season-2-1',
    episodeNumber: 3,
    title: 'Double Cross',
    description: 'A key informant is silenced right before revealing the mastermind behind the commissioner office leak.',
    videoUrl: SAMPLE_VIDEOS[3],
    thumbnailUrl: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=800&auto=format&fit=crop&q=80',
    duration: 160,
    durationFormatted: '2m 40s',
    releaseDate: '2025-02-21',
    status: 'Published',
    orderIndex: 3,
    viewsCount: 8100,
    likesCount: 620,
    commentsCount: 28,
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'ep-2-4',
    seriesId: 'series-2',
    seasonId: 'season-2-1',
    episodeNumber: 4,
    title: 'High Velocity',
    description: 'High-speed pursuit down the Eastern Freeway as bullets fly through the morning smog.',
    videoUrl: SAMPLE_VIDEOS[4],
    thumbnailUrl: 'https://images.unsplash.com/photo-1508974239320-0a029497e820?w=800&auto=format&fit=crop&q=80',
    duration: 195,
    durationFormatted: '3m 15s',
    releaseDate: '2025-02-25',
    status: 'Published',
    orderIndex: 4,
    viewsCount: 7500,
    likesCount: 590,
    commentsCount: 30,
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'ep-2-5',
    seriesId: 'series-2',
    seasonId: 'season-2-1',
    episodeNumber: 5,
    title: 'Checkmate',
    description: 'In a rooftop face-off above Nariman Point, Raghav must decide between revenge and upholding justice.',
    videoUrl: SAMPLE_VIDEOS[5],
    thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    duration: 220,
    durationFormatted: '3m 40s',
    releaseDate: '2025-03-01',
    status: 'Published',
    orderIndex: 5,
    viewsCount: 6800,
    likesCount: 540,
    commentsCount: 42,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },

  // Series 3 Episodes (Love at First Beat)
  {
    id: 'ep-3-1',
    seriesId: 'series-3',
    seasonId: 'season-3-1',
    episodeNumber: 1,
    title: 'Chennai Cypher',
    description: 'Karthik drops an electrifying Tamil rap freestyle under the metro bridge that goes viral overnight.',
    videoUrl: SAMPLE_VIDEOS[2],
    thumbnailUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    duration: 150,
    durationFormatted: '2m 30s',
    releaseDate: '2025-03-01',
    status: 'Published',
    isFeatured: true,
    orderIndex: 1,
    viewsCount: 6200,
    likesCount: 520,
    commentsCount: 26,
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    id: 'ep-3-2',
    seriesId: 'series-3',
    seasonId: 'season-3-1',
    episodeNumber: 2,
    title: 'Raga Meets 808',
    description: 'Meera accidentally books the same Bangalore rehearsal studio. An argument turns into an impromptu jam session.',
    videoUrl: SAMPLE_VIDEOS[3],
    thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
    duration: 170,
    durationFormatted: '2m 50s',
    releaseDate: '2025-03-03',
    status: 'Published',
    orderIndex: 2,
    viewsCount: 5100,
    likesCount: 430,
    commentsCount: 21,
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'ep-3-3',
    seriesId: 'series-3',
    seasonId: 'season-3-1',
    episodeNumber: 3,
    title: 'The Audition',
    description: 'A premier record label producer offers them a chance, but demands Meera drop her traditional ensemble.',
    videoUrl: SAMPLE_VIDEOS[4],
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    duration: 165,
    durationFormatted: '2m 45s',
    releaseDate: '2025-03-05',
    status: 'Published',
    orderIndex: 3,
    viewsCount: 4400,
    likesCount: 380,
    commentsCount: 17,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'ep-3-4',
    seriesId: 'series-3',
    seasonId: 'season-3-1',
    episodeNumber: 4,
    title: 'Harmony in Chaos',
    description: 'Pressured by families from opposite backgrounds, Karthik and Meera find solace composing on a rooftop terrace.',
    videoUrl: SAMPLE_VIDEOS[0],
    thumbnailUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&auto=format&fit=crop&q=80',
    duration: 180,
    durationFormatted: '3m 00s',
    releaseDate: '2025-03-07',
    status: 'Published',
    orderIndex: 4,
    viewsCount: 3900,
    likesCount: 320,
    commentsCount: 15,
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'ep-3-5',
    seriesId: 'series-3',
    seasonId: 'season-3-1',
    episodeNumber: 5,
    title: 'Final Chord',
    description: 'At the grand Music Fest finale, they risk everything to perform their fusion masterpiece live.',
    videoUrl: SAMPLE_VIDEOS[1],
    thumbnailUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80',
    duration: 205,
    durationFormatted: '3m 25s',
    releaseDate: '2025-03-09',
    status: 'Published',
    orderIndex: 5,
    viewsCount: 3500,
    likesCount: 290,
    commentsCount: 24,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
